version: "3.7"
services:
  mysql:
    image: mysql:5.6
    ports:
      - ${PORT}:3306
    deploy:
      mode: global
      resources:
        limits:
          memory: ${MAX_MEMORY}
        reservations:
          memory: ${MIN_MEMORY}
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    
volumes:
  db_data: